# -*- coding: utf-8 -*-
"""SplittingFolders.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WpMzgBWO4kaIAS1shOcijagKof5iCPkS
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import shutil
import random

root_dir = "/content/drive/My Drive/curetDataSet/CURET_TEXTURE/"

test_dir = "/content/drive/My Drive/curetDataSet/Test/"

files = os.listdir(root_dir)

for f in files:
  if np.random.rand(1) < 0.05:
    shutil.move(root_dir + '/'+ f, test_dir + '/'+ f)

train_dir = "/content/drive/My Drive/curetDataSet/Train/"

valid_dir = "/content/drive/My Drive/curetDataSet/Valid/"

classes_dir = ["01",
"02",
"03",
"04",
"05",
"06",
"07",
"08",
"09",
"10",
"11",
"12",
"13",
"14",
"15",
"16",
"17",
"18",
"19",
"21",
"22",
"23",
"24",
"25",
"26",
"27",
"28",
"29",
"30",
"31",
"32",
"33",
"34",
"35",
"36",
"37",
"38",
"39",
"40",
"41",
"42",
"43",
"44",
"45",
"46",
"47",
"48",
"49",
"50",
"51",
"52",
"53",
"54",
"55",
"56",
"57",
"58",
"59",
"60",
"61"
               ]

val_ratio = 0.15
test_ratio = 0.05

for cls in classes_dir:
  os.makedirs(train_dir + cls)
  os.makedirs(valid_dir + cls)
  os.makedirs(test_dir + cls)

  src = root_dir + cls

  allFileNames = os.listdir(src)
  np.random.shuffle(allFileNames)
  train_FileNames, val_FileNames, test_FileNames = np.split(np.array(allFileNames),
                                                            [int(len(allFileNames)* (1 - val_ratio + test_ratio)),
                                                             int(len(allFileNames)* (1 - test_ratio))]
                                                            )
  train_FileNames = [src+'/'+ name for name in train_FileNames.tolist()]
  val_FileNames = [src + '/' + name for name in val_FileNames.tolist()]
  test_FileNames = [src + '/' + name for name in test_FileNames.tolist()]

  for name in train_FileNames:
    shutil.copy(name, train_dir + cls)

  for name in val_FileNames:
    shutil.copy(name, valid_dir + cls)

  for name in test_FileNames:
    shutil.copy(name, test_dir + cls)